services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: YOUR_APP_KEY
      - key: DB_CONNECTION
        value: YOUR_DB_CONNECTION
      - key: DB_HOST
        value: YOUR_DB_HOST
      - key: DB_PORT
        value: YOUR_DB_PORT
      - key: DB_DATABASE
        value: YOUR_DB_DATABASE
      - key: DB_USERNAME
        value: YOUR_DB_USERNAME
      - key: DB_PASSWORD
        value: YOUR_DB_PASSWORD
